set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/examples)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/examples)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/examples)
link_libraries(xcal xcal_opengl xcal_imgui xcal_glfw)

add_executable(circle circle.cc)
add_executable(path path.cc)
add_executable(axis axis.cc)
add_executable(destruct destruct.cc)
add_executable(line line.cc)
add_executable(openglrender openglrender.cc)
